export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SET_NEW_POST_MODAL_TAB = "SET_NEW_POST_MODAL_TAB";
export const SET_NEW_POST_IMAGE_ASPECT_RATIO =
  "SET_NEW_POST_IMAGE_ASPECT_RATIO";
export const SET_NEW_POST_IMAGES = "SET_NEW_POST_IMAGES";
export const SET_NEW_POST_IMAGES_ZOOM = "SET_NEW_POST_IMAGES_ZOOM";
export const SET_NEW_POST_IMAGE_INDEX = "SET_NEW_POST_IMAGE_INDEX";
export const SET_NEW_POST_IMAGE_SCROLL = "SET_NEW_POST_IMAGE_SCROLL";
export const PROCESS_CROPPING_OF_IMAGES = "PROCESS_CROPPING_OF_IMAGES";
export const SET_NEW_POST_MODAL_WINDOW_WIDTH =
  "SET_NEW_POST_MODAL_WINDOW_WIDTH";
export const RESET_MODAL_STATE = "RESET_MODAL_STATE";
export const POST_NEW_POST = "POST_NEW_POST";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILES_BY_IDS = "GET_USER_PROFILES_BY_ID";

export const REMOVE_PROFILE_IMAGE = "REMOVE_PROFILE_IMAGE";
export const CHANGE_PROFILE_IMAGE = "CHANGE_PROFILE_IMAGE";
export const SET_NEW_POST_DECRIPTION = "SET_NEW_POST_DECRIPTION";
export const GET_PROFILE_POSTS = "GET_PROFILE_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const GET_COMMENTS_BY_POST_ID = "GET_COMMENTS_BY_POST_ID";
export const LIKE_POST = "LIKE_POST";
export const REMOVE_POST_LIKE = "REMOVE_POST_LIKE";
export const FOLLOW_USER = "FOLLOW_USER";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const GET_USERS_WHO_LIKED = "GET_USERS_WHO_LIKED";
