export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SET_NEW_POST_MODAL_TAB = "SET_NEW_POST_MODAL_TAB";
export const SET_NEW_POST_IMAGE_ASPECT_RATIO =
  "SET_NEW_POST_IMAGE_ASPECT_RATIO";
export const SET_NEW_POST_IMAGES = "SET_NEW_POST_IMAGES";
export const SET_NEW_POST_IMAGES_ZOOM = "SET_NEW_POST_IMAGES_ZOOM";
export const SET_NEW_POST_IMAGE_INDEX = "SET_NEW_POST_IMAGE_INDEX";
export const SET_NEW_POST_IMAGE_SCROLL = "SET_NEW_POST_IMAGE_SCROLL";
export const PROCESS_CROPPING_OF_IMAGES = "PROCESS_CROPPING_OF_IMAGES";
export const SET_NEW_POST_MODAL_WINDOW_WIDTH =
  "SET_NEW_POST_MODAL_WINDOW_WIDTH";
export const RESET_MODAL_STATE = "RESET_MODAL_STATE";
export const POST_NEW_POST = "POST_NEW_POST";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
